### ISSUE TITLE
Registering a user via the login page does not add the user to the users table

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#23] opened 2018-10-11 18:31 UTC
If a user successfully registers a new account, the admin cannot approve the account because it does not show up in the table on the users page.

All browsers.

Recreate: Register a new user via the login page. Then login as admin and visit the users page.

**Comment by EagleZR** [comment] 2018-10-11 22:05
Unable to reproduce, registering added a new user to the user's table. Closing

**Closed by EagleZR** 2018-10-11 22:05 UTC
Labels: bug
